### ISSUE TITLE
Add possibility to read `pars`

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendDataManagement.jl#11]
We need a `pars` reader which works in the same fashion as the metadata reader. It should respect the validity files and just read the propdicts out of the `pars` folder instead of the metadata folder. 
It should work like 
``` julia
calib_pars = l200.par.cal(ValiditySelection)[detector]
```
The folder for `cal` currently contains then the period name and runs following. But, it would be nice to have the validity selection independent of the runs and periods. so the selection should be possible on the `cal` folder level. In addition, a feature like 
``` julia
calib_pars = l200.par.cal[period, run]
```
would also be nice to just get pars for a specific run. 
I think this should be straightforward to implement. 
Maybe I can make a draft PR and then we see how this looks like. Or @oschulz, do you have some time?

**Comment by oschulz** [comment]
I'll see that I do that next week - but remind me :-)

**Comment by theHenks** [comment]
Thanks to @fhagemann , there is already a draft version on the ceph. He implemented a similar functionality than we have for the metadata and config reader. Looks very very nice, so big thanks to Felix!

**Comment by oschulz** [comment]
Can we close this now?
