### ISSUE TITLE
Overwrite Functionality for `dataprod` config

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendDataManagement.jl#32]
We should add the following functionalities to be able to overwrite things in the official `dataprod`:
- Create a `partitions.json` in the `jldataprod` and refer the `partitioninfo` to that one. This makes us more flexible in terms of partitioning. 
- Create functionality to overwrite the channel map in the `jldataprod` in particular to be able to set our own `psd_status` and so on and not depend on `pygama` main analysis

**Comment by theHenks** [comment]
Also to be included:
Functionality to overwrite `validity.jsonl` auto-generated files for e.g. backwards calibrations and other things to not mess with the data production itself.

**Comment by theHenks** [comment]
@gipert

**Comment by gipert** [comment]
done
