### ISSUE TITLE
Exposure calculation

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendDataManagement.jl#33]
Add functionality to get the exposure for a list of filekeys .
The function should:
- iterate through the filekeys
- get the corresponding channel maps
- get the `livetime_in_ns` from the runinfo 
- calculate the exposure per detector and return the corresponding exposure. 
The return should contain the exposure per channel and maybe additionally also information form the `metadata` such as enrichment, dead layer, active volume etc.

**Comment by theHenks** [comment]
Maybe something for @fhagemann and the interns?

**Comment by fhagemann** [comment]
We could have a look into this

**Comment by theHenks** [comment]
@gipert

**Comment by gipert** [comment]
done

**Comment by fhagemann** [comment]
I think all the functionality required to write this function should be there.
What do want exaclty? Just one value for the exposure for a set of filekeys? Or exposure listed per detector?

**Comment by fhagemann** [comment]
It was discussed:
return the exposure for a given `DetectorId` and `Partition` with the lifetime extracted from either `runinfo` or `partitioninfo`.
