### ISSUE TITLE
Plot recipes for pars

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendDataManagement.jl#46]
Include plot recipe for plotting of pars where a selected value is on the y axis and all detectors are on the x-axis.

**Comment by theHenks** [comment]
@fhagemann Reminder

**Comment by theHenks** [comment]
@gipert

**Comment by gipert** [comment]
done

**Comment by theHenks** [comment]
@fhagemann Resolve issue with type piracy, ready apart from that!
